export const actions = {
    SET_SIDEBAR_VISIBILITY: 'SET_SIDEBAR_VISIBILITY',
    SET_BOTTOMBAR_VISIBILITY: 'SET_BOTTOMBAR_VISIBILITY',
    SET_ACTIVE_SIDEBAR_OPTION: 'SET_ACTIVE_SIDEBAR_OPTION',
    ADD_OPTION_TO_VISITED: 'ADD_OPTION_TO_VISITED',
};