export const actions = {
    SET_SIDEBAR_VISIBILITY: 'SET_SIDEBAR_VISIBILITY',
    SET_BOTTOMBAR_VISIBILITY: 'SET_BOTTOMBAR_VISIBILITY',
    SET_ACTIVE_SIDEBAR_OPTION: 'SET_ACTIVE_SIDEBAR_OPTION',
    ADD_OPTION_TO_VISITED: 'ADD_OPTION_TO_VISITED',
    ADD_COMMIT: 'ADD_COMMIT',
    RESIZE_SVG_CONTENT: 'RESIZE_SVG_CONTENT',
    ADD_REF: 'ADD_REF',
    CHECKOUT_REF: 'CHECKOUT_REF',
    SUBMIT_COMMAND: 'SUBMIT_COMMAND',
    MOVE_TO_EXERCISE: 'MOVE_TO_EXERCISE',
    MOVE_TO_CONTENT: 'MOVE_TO_CONTENT',
};

export const exerciseActions = {
    CHECK_EXERCISE_STATUS: 'CHECK_EXERCISE_STATUS',
};
