export const actions = {
    SET_SIDEBAR_VISIBILITY: 'SET_SIDEBAR_VISIBILITY',
    SET_BOTTOMBAR_VISIBILITY: 'SET_BOTTOMBAR_VISIBILITY',
    SET_ACTIVE_SIDEBAR_OPTION: 'SET_ACTIVE_SIDEBAR_OPTION',
    ADD_OPTION_TO_VISITED: 'ADD_OPTION_TO_VISITED',
    ADD_COMMIT: 'ADD_COMMIT',
    ADD_REF: 'ADD_REF',
    CHECKOUT_REF: 'CHECKOUT_REF',
    CHECKOUT_REF_B: 'CHECKOUT_REF_B',
    CREATE_REF_FROM_REF: 'CREATE_REF_FROM_REF',
    CREATE_AND_CHECKOUT_REF_FROM_REF: 'CREATE_AND_CHECKOUT_REF_FROM_REF',
    ADD_MERGE_COMMIT: 'ADD_MERGE_COMMIT',
    REBASE: 'REBASE',
    RESET: 'RESET',
    PULL: 'PULL',
    MOVE_TO_EXERCISE: 'MOVE_TO_EXERCISE',
    MOVE_TO_CONTENT: 'MOVE_TO_CONTENT',
};

export const exerciseActions = {
    CHECK_EXERCISE_STATUS: 'CHECK_EXERCISE_STATUS',
};
